version: '3'
services:        
    web: &django
        build:
          context: .
          dockerfile: ./Dockerfile
       # restart: always
        ports:
        - "8001:8001"
        volumes:
        - .:/app2
        external_links:
        - nginx
        - postgres
        - nginx_mailhog_1
        - nginx_redis_1
        
        command: ["bash", "/start.sh" ]
